version: '3'

tasks:
  build:
    cmds:
      - docker compose build --progress=plain
  up:
    cmds:
      - docker compose up
  up-d:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  restart:
    cmds:
      - docker compose restart {{.CLI_ARGS}} -no-d
  clean:
    cmds:
      - docker rmi $(docker ps -a -q -f name=^docker-persistence-layer-*) || true
      - docker volume rm -f $(docker volume ls -q -f name=^docker-persistence-layer-*) || true
  logs:
    cmds:
      - docker compose logs -f
  clean-and-up:
    cmds:
      - task: down
      - task: clean
      - task: build
      - task: up
  pull:
    cmds:
      - docker compose pull
