#!/bin/bash -eux

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" --dbname postgres <<-EOSQL
	DROP DATABASE IF EXISTS $POSTGRES_DB;
	CREATE DATABASE $POSTGRES_DB WITH LC_COLLATE = 'ja_JP.utf8' LC_CTYPE = 'ja_JP.utf8' TEMPLATE template0;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL
