#!/bin/bash
set -e

if command -v psql &> /dev/null
then
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"  <<-EOSQL
	    CREATE USER IF NOT EXIST ${POSTGRES_USER} WITH PASSWORD '${POSTGRES_PASSWORD}';
	    CREATE DATABASE ${POSTGRES_DB};
	    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
EOSQL
fi
