name: Build and push images

on:
    workflow_dispatch:
    push:
      branches: [ 'main' ]
      tags: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and push images
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      UNAME: ${{ vars.DOCKER_HUB_USERNAME }}
    steps:
      - uses: actions/checkout@v4
      - name: get tag name
        run: |
          if [ -z "${GITHUB_REF##refs/tags/*}" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "main" ]; then
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          else
            exit 1
          fi
      - name: echo $TAG_NAME
        run: echo "${{ env.TAG_NAME }}"
      - name: Set $BUILD_ARGS
        run: |
          echo "BUILD_ARGS=$(cat .env | tr '\n' ',' | sed 's/,,/,/g')" >> $GITHUB_ENV
      - name: echo $BUILD_ARGS
        run: echo "${{ env.BUILD_ARGS }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.UNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push mysql image
        uses: docker/build-push-action@v5
        with:
          context: ./mysql
          push: true
          file: ./mysql/Dockerfile
          tags: ${{ env.UNAME }}/mysql:${{ env.TAG_NAME }}
          build-args: ${{ env.BUILD_ARGS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: linux/amd64,linux/arm64/v8
      - name: Build and push postgres image
        uses: docker/build-push-action@v5
        with:
          context: ./postgres
          push: true
          file: ./postgres/Dockerfile
          tags: ${{ env.UNAME }}/postgres:${{ env.TAG_NAME }}
          build-args: ${{ env.BUILD_ARGS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: linux/amd64,linux/arm64/v8
      - name: Build and push redis image
        uses: docker/build-push-action@v5
        with:
          context: ./redis
          push: true
          file: ./redis/Dockerfile
          tags: ${{ env.UNAME }}/redis:${{ env.TAG_NAME }}
          build-args: ${{ env.BUILD_ARGS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: linux/amd64,linux/arm64/v8
      - name: Move new cache to the place where to be cached
        run: |
          echo "Temporary fix for cleaning up old cache."
          echo "See isssues:
            - https://github.com/docker/build-push-action/issues/252
            - https://github.com/moby/buildkit/issues/1896
          "
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
